# Generated by Django 2.2.17 on 2020-12-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_new_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_test_length', models.BigIntegerField()),
                ('first_name_test_length2', models.BigIntegerField(blank=True, null=True)),
                ('first_name_test_length3', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
